version: '3.8'

services:
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 sit.asgi:application
    volumes:
      - .:/app
    expose:
      - "8000"
    env_file:
      - .env.production
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/home/ubun/sit/statics
      - media_volume:/home/ubun/sit/media
    depends_on:
      - web
  redis:
    image: redis:alpine
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postdatabase
      POSTGRES_USER: ubun
      POSTGRES_PASSWORD: asdfmypassword
  celery:
    build: .
    command: celery -A sit worker --loglevel=info
    depends_on:
      - redis
      - db
volumes:
  postgres_data:
  static_volume:
  media_volume:
