# Generated by Django 5.1.8 on 2025-06-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('text', models.TextField()),
                ('start', models.DateTimeField()),
                ('due', models.DateTimeField()),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High')], default='Normal', max_length=6)),
                ('recurrence', models.CharField(choices=[('N', 'None'), ('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly')], default='N', max_length=1)),
            ],
        ),
    ]
